# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'Sports Tracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sports Tracker
  # Realm Database
  pod 'RealmSwift', '10.14.0'
  #Google Firebase
  pod 'Firebase/Auth'
  pod 'FirebaseFirestoreSwift'
end
